### ISSUE TITLE
[Feedback] API Impressions

### ISSUE THREAD

**Issue by jakehamilton** [roecrew/zam#7]
Hi, after playing around for a little bit with Zam I've written up a couple of comments on this pen: https://codepen.io/short/pen/RxxEOE.

Namely:

```js
super('<div class="toggle"></div>')
```

+ This feels like boilerplate
+ The passing of an html string seems odd, perhaps there's a better way to structure this?

```js
const checkbox = new Zam(`
  <input type="checkbox" id="${id}" class="checkbox">
`)
```

+ Still strange to be passing html strings around when it doesn't seem like there's much of a reason

```js
this.append(checkbox)
```

+ I wonder if there is a better way to compose components rather than this `ZamInstance.append` method, it feels a bit boilerplate-y still.

```js
checkbox.on('click', () => {
      // toggle a class somehow?
      // I have no idea how you would dynamically change a class
      //  on a Zam instance, it isn't in the docs.
    })
```

+ Some work could be done to have class methods bound to the instance, especially event callbacks
+ The docs don't seem to say anything about getting/setting html properties (if that is something Zam can do)

-----

All that said, great work so far :smile:

**Comment by roecrew** [comment]
- Thank you for your feedback!

"This feels like boilerplate
The passing of an html string seems odd, perhaps there's a better way to structure this?"
"I wonder if there is a better way to compose components"

- This is something I have been going back and forth on for some time.


"I have no idea how you would dynamically change a class"

- I haven't documented that one :/.

You would have to use the "element property" like this.
```javascript
  checkbox.e.className = "thisISmyCLASS"
```

**Comment by jakehamilton** [comment]
@roecrew, thanks for getting back to me so quickly!

> `checkbox.e.className = ...`

Is `ZamInstance.e` a normal `HTMLElement`?

-----

Perhaps I'm not quite sure what the library is trying to be? It seems to want to be a jQuery-like web-component library, and, in doing so, ends up feeling like it doesn't do either one too well. If this is the case then maybe zeroing in on the single purpose of the library will help with the interface issues?

**Comment by roecrew** [comment]
"Is ZamInstance.e a normal HTMLElement?"

 - Correct.

"It seems to want to be a jQuery-like web-component library, and, in doing so, ends up feeling like it doesn't do either one too well."

- I completely agree.

**Comment by roecrew** [comment]
@jakehamilton 

"It seems to want to be a jQuery-like web-component library, and, in doing so, ends up feeling like it doesn't do either one too well."

- Actually, I don't agree entirely. But the fact that it comes off as jQueryish concerns me.

**Comment by jakehamilton** [comment]
@roecrew, I think what is making the connection between Zam and jQuery is the more imperative (and somewhat similar) style api.

```js
// jQuery
const el = $('<div></div>')
$('.root').append(el)

el.css(...)

el.html('Hello World')

// Zam
const el = new Zam('<div></div>')
el.mount('.root')

el.setCSS(...)

el.setInnerHTML('Hello World')
```

If the goal is web components, then I see that Zam has some great potential. IMO the biggest hurdle is going to be finding the right interface that feels good to use, exposes all of the features you need, and isn't overly verbose. I wonder if doing something in the same vein `lit-html` would be a good idea?

**Comment by roecrew** [comment]
@jakehamilton 

I added .render() and .shadowRender()

Your thoughts? If you are interested, then see the second example on the README.

**Comment by jakehamilton** [comment]
@roecrew 

It's starting to feel more like native custom elements (ex. https://codepen.io/short/pen/BJYXjx) but giving up a few features that Zam doesn't support (watched attributes, lifecycle hooks, etc). Perhaps we should take a step back and really think about what it is that Zam is going to do better than the native solutions? Data binding in templates, for example, would be a very useful feature on top of native custom elements.

**Comment by roecrew** [comment]
@jakehamilton 

My only concern with native custom elements is the current support.
<img width="1066" alt="screen shot 2018-01-10 at 12 34 14 pm" src="https://user-images.githubusercontent.com/6314185/34789150-be290b4e-f602-11e7-8660-411f2fb56dae.png">

I'd really like to incorporate .define(), but the support just isn't there yet.

**Comment by roecrew** [comment]
@jakehamilton 

I implemented a pretty simple data-binding.
I also cut back on most of the functions.

**Comment by jakehamilton** [comment]
Maybe a useful exercise would be taking a step back from the implementation and deciding what exactly the goal of Zam is. By that I mean, we have pollyfills and other libraries for web components. Is Zam meant to copy them? Or is the goal of Zam to provide something that these libraries are missing? Is it meant to be a standalone or to complement those other web component libraries?

I think once those questions are answered we can think about what the ideal interface would be for the use case.

**Comment by roecrew** [comment]
@jakehamilton 
I just pushed an update. Zam is far simpler and different now.
