### ISSUE TITLE
[BUG] Received a campaign email but never opt-in

### ISSUE THREAD

**Issue by BinotaLIU** [roecrew/zam#8]
Hi there,
I received a campaign e-mail but I have never opt-in. I think you add me to the list in a mistake.

![image](https://user-images.githubusercontent.com/3190556/34706937-662fc184-f545-11e7-9dfb-fadc381f3a55.png)

**Comment by roecrew** [comment]
@BinotaLIU 
I did a bulky scrap of github emails. I'll take you off the list immediately.

**Comment by sertaconay** [comment]
wow that's why I'm here as well. This project or library (whatever it's called) is a side project yet and the owner shouldn't send spam to announce it's released. bad reputation. hope you fix it in the future.

**Comment by roecrew** [comment]
@sertaconay

I'll definitely take this into account.
My apologies. I was thinking of it as promotion, not spam.
But I see where you are coming from.

I'm just excited about my project. :)

**Comment by BinotaLIU** [comment]
It is cool that a new JavaScript library has been released.
But sending people email without asking they to opt-in is not :)
